"""Tests for verbatim inclusion of external report files in the digest."""

import os
import time

from lookout.digest import DigestBuffer, include_file_section, send_digest


def test_includes_file_content_verbatim(tmp_path):
    report = tmp_path / "report.md"
    report.write_text("# Site monitor report\n\nNo content changes since the last report.\n")
    section = include_file_section(str(report), period_hours=24)
    assert "# Site monitor report" in section
    assert "No content changes" in section
    assert "[Note" not in section


def test_missing_file_is_called_out(tmp_path):
    section = include_file_section(str(tmp_path / "absent.md"), period_hours=24)
    assert "not found" in section
    assert "absent.md" in section


def test_stale_file_is_flagged(tmp_path):
    report = tmp_path / "report.md"
    report.write_text("# Site monitor report\n")
    two_days_ago = time.time() - 48 * 3600
    os.utime(report, (two_days_ago, two_days_ago))
    section = include_file_section(str(report), period_hours=24)
    assert "# Site monitor report" in section
    assert "older than the digest period" in section


class _FakeAI:
    label = "Fake / model"

    def complete(self, prompt: str) -> str:
        return "AI SUMMARY"


class _FakeAlerter:
    def __init__(self) -> None:
        self.sent: list[str] = []

    def send_digest(self, body: str) -> None:
        self.sent.append(body)


def test_ai_attribution_precedes_included_reports(tmp_path):
    report = tmp_path / "report.md"
    report.write_text("# Site monitor report\n")
    alerter = _FakeAlerter()
    send_digest(
        DigestBuffer(),
        _FakeAI(),
        alerter,
        docker_url="unix:///nonexistent.sock",
        period_hours=24,
        include_files=[str(report)],
    )
    body = alerter.sent[0]
    assert body.index("Generated by Fake / model") < body.index("# Site monitor report")
