import logging
import time
from collections import deque
from datetime import UTC, datetime, timedelta
from pathlib import Path
from threading import Lock

from lookout.alerter import Alerter
from lookout.analyzer import AIProvider, digest_prompt
from lookout.exposure import scan_exposure
from lookout.models import Alert, LogEntry

logger = logging.getLogger(__name__)


class DigestBuffer:
    def __init__(self, maxsize: int = 50_000) -> None:
        self._buf: deque[LogEntry] = deque(maxlen=maxsize)
        self._findings: deque[tuple[datetime, Alert]] = deque(maxlen=maxsize)
        self._lock = Lock()

    def add(self, entry: LogEntry) -> None:
        with self._lock:
            self._buf.append(entry)

    def add_finding(self, alert: Alert) -> None:
        # Non-immediate alerts (probes, scanning, failed brute force) surface in the digest.
        with self._lock:
            self._findings.append((datetime.now(UTC).replace(tzinfo=None), alert))

    def entries_since(self, hours: int) -> list[LogEntry]:
        cutoff = datetime.now(UTC).replace(tzinfo=None) - timedelta(hours=hours)
        with self._lock:
            return [e for e in self._buf if e.timestamp >= cutoff]

    def findings_since(self, hours: int) -> list[Alert]:
        cutoff = datetime.now(UTC).replace(tzinfo=None) - timedelta(hours=hours)
        with self._lock:
            return [a for ts, a in self._findings if ts >= cutoff]


def include_file_section(path: str, period_hours: int) -> str:
    """Render an external report file for verbatim inclusion in the digest.

    The content is appended as-is (not fed to the AI model). A missing or stale file is
    reported rather than silently skipped — for a monitoring digest, absence is signal.
    """
    file = Path(path)
    if not file.is_file():
        return f"[Report file {path} not found — the tool that writes it may not have run.]"
    content = file.read_text(errors="replace").strip()
    age_hours = (time.time() - file.stat().st_mtime) / 3600
    if age_hours > period_hours:
        content += (
            f"\n\n[Note: this report file is {age_hours:.0f}h old — older than the digest"
            " period, so it may be out of date.]"
        )
    return content


def send_digest(
    buffer: DigestBuffer,
    ai: AIProvider,
    alerter: Alerter,
    docker_url: str,
    period_hours: int = 24,
    include_files: list[str] | None = None,
) -> None:
    logger.info("generating digest for the last %dh", period_hours)
    entries = buffer.entries_since(period_hours)
    findings = buffer.findings_since(period_hours)
    exposures = scan_exposure(docker_url)
    prompt = digest_prompt(entries, findings, exposures, period_hours=period_hours)
    try:
        summary = ai.complete(prompt)
        # Attribute the AI where its text ends — the included reports below are verbatim,
        # not model output.
        body = f"{summary}\n\nGenerated by {ai.label}"
        for path in include_files or []:
            body += "\n\n---\n\n" + include_file_section(path, period_hours)
        alerter.send_digest(body)
    except Exception:
        logger.exception("digest generation failed")
