name: Clean up untagged images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete untagged images
        uses: actions/delete-package-versions@v5
        with:
          package-name: lookout
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
