name: Clean up untagged images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete untagged images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: lookout
          delete-untagged: true
          delete-ghost-images: true
          validate: true
